// ---------------------------------------------------------------------------
// First-run setup utilities
// ---------------------------------------------------------------------------

import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import crypto from 'crypto';

const ENV_PATH = join(process.cwd(), '.env');

/** Check whether the app has been configured (has NEXTAUTH_SECRET in .env). */
export function isSetupComplete(): boolean {
  // Fast path: check env var in memory first
  if (process.env.NEXTAUTH_SECRET && process.env.NEXTAUTH_SECRET !== '') {
    return true;
  }

  // Check .env file on disk
  if (!existsSync(ENV_PATH)) return false;
  const content = readFileSync(ENV_PATH, 'utf-8');
  return content.includes('NEXTAUTH_SECRET=') && !content.includes('NEXTAUTH_SECRET=""');
}

/** Generate a cryptographically secure random secret. */
export function generateSecret(bytes = 32): string {
  return crypto.randomBytes(bytes).toString('base64url');
}

export interface SetupConfig {
  // App
  appUrl: string;

  // GitHub OAuth (for user login)
  githubClientId: string;
  githubClientSecret: string;

  // GitHub App (for PR reviews) — optional
  githubAppId?: string;
  githubAppPrivateKey?: string;
  githubAppWebhookSecret?: string;
  githubAppSlug?: string;
  githubAppClientId?: string;
  githubAppClientSecret?: string;

  // Analysis
  analysisBackends: string;

  // Admin
  adminEmail: string;
  adminName: string;
}

/** Build the .env file content from setup config. */
export function buildEnvContent(config: SetupConfig): string {
  const nextauthSecret = generateSecret();
  const webhookSecret = config.githubAppWebhookSecret || generateSecret(20);

  const lines = [
    `# CodeAnalyzer Configuration`,
    `# Generated by first-run setup on ${new Date().toISOString()}`,
    ``,
    `DATABASE_URL="file:./dev.db"`,
    ``,
    `# NextAuth`,
    `NEXTAUTH_SECRET="${nextauthSecret}"`,
    `NEXTAUTH_URL="${config.appUrl}"`,
    ``,
    `# GitHub OAuth (user login)`,
    `GITHUB_CLIENT_ID="${config.githubClientId}"`,
    `GITHUB_CLIENT_SECRET="${config.githubClientSecret}"`,
    ``,
    `# GitHub App (PR reviews)`,
    `GITHUB_APP_ID="${config.githubAppId || ''}"`,
    `GITHUB_APP_PRIVATE_KEY="${config.githubAppPrivateKey || ''}"`,
    `GITHUB_APP_WEBHOOK_SECRET="${webhookSecret}"`,
    `GITHUB_APP_SLUG="${config.githubAppSlug || ''}"`,
    `GITHUB_APP_CLIENT_ID="${config.githubAppClientId || ''}"`,
    `GITHUB_APP_CLIENT_SECRET="${config.githubAppClientSecret || ''}"`,
    ``,
    `# Analysis`,
    `ANALYSIS_BACKENDS="${config.analysisBackends}"`,
    ``,
    `# Admin`,
    `ADMIN_EMAIL="${config.adminEmail}"`,
    ``,
  ];

  return lines.join('\n');
}
